triggers:
  - name: trigger1
    type: trigger
    version:
      counter: 63
      
  - name: trigger2
    type: trigger
    version:
      counter: 428

  - name: trigger3
    type: trigger
    version:
      counter: 0
